name: "cloudreve_view"
description: "secret"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  get: ^4.6.6
  dio: ^5.7.0
  shared_preferences: ^2.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  photo_view: ^0.15.0
  cached_network_image: ^3.4.0
  video_player: ^2.8.2



  intl: any
  flutter_turnstile: ^1.2.0
  flutter_svg: ^2.0.10+1
  webview_windows:
    path: third_party/webview_windows
  url_launcher: ^6.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^3.0.0
  build_runner: ^2.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/pic.png
    - assets/images/start_bg.gif
# flutter_intl:
#   enabled: true
#   template-arb-file: lib/l10n/app_zh.arb
#   output-localization-file: lib/l10n/app_localizations.dart
